#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007, 2009, 2010, 2012 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
#
# Init file for zmail mail
#
# chkconfig: 345 99 01
# description: Zmail mail service
#
### BEGIN INIT INFO
# Provides:       zmail
# Required-Start: $network $remote_fs $syslog $time nscd cron
# Required-Stop:  $network $remote_fs $syslog $time
# Default-Start:  3 5
# Description:    Zmail mail service
### END INIT INFO


command()
{
	if [ -f /opt/zmail/redolog/redo.log ]; then
		chown -f zmail:zmail /opt/zmail/redolog/redo.log
	fi
	# su - zmail -c "zmcontrol $1 </dev/null >>/opt/zmail/log/startup.log 2>&1"
	# bug 45842
	su - zmail -c "zmcontrol $1 </dev/null"
}

case "$1" in
	restart)
		command shutdown
		command startup
		RETVAL=$?
    if [ -d /var/lock/subsys -a $RETVAL -eq 0 ]; then
      touch /var/lock/subsys/zmail
    fi
		;;
	start)
		command startup
		RETVAL=$?
    if [ -d /var/lock/subsys -a $RETVAL -eq 0 ]; then
      touch /var/lock/subsys/zmail
    fi
		;;
	stop)
		command shutdown
		RETVAL=$?
    if [ -d /var/lock/subsys -a $RETVAL -eq 0 ]; then
      rm -f /var/lock/subsys/zmail
    fi
		;;
	reload|status)
		command $1
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		RETVAL=1
esac
exit $RETVAL
