#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2010, 2011, 2012 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

source `dirname $0`/../bin/zmshutil || exit 1
zmsetvars \
    zmail_home \
    zmail_log_directory \
    zmail_db_directory \
    antispam_mysql_mycnf \
    antispam_mysql_data_directory \
    antispam_mysql_directory \
	mysql_directory

sql_root_pw=$1

#
# Sanity checks
#
zmassert -x ${zmail_home}/bin/antispam-mysqladmin
zmassert -x ${zmail_home}/bin/antispam-mysql
zmassert -x ${zmail_home}/bin/zmlocalconfig
zmassert -x ${zmail_home}/bin/zmantispamdbpasswd
zmassert -x ${antispam_mysql_directory}/scripts/mysql_install_db
zmassert -r ${zmail_home}/data/amavisd/mysql/antispamdb.sql

#
# Create necessary directories
#
#echo '*' Creating required directories
#mkdir -p ${antispam_mysql_data_directory}
#chmod -R 755 /opt/zmail/data/amavisd/mysql

# Check if log directory exists.  If not, create.
if [ ! -d ${zmail_log_directory} ]; then
	mkdir -p ${zmail_log_directory}
fi

#
# Create antispam-my.cnf file if it does not exist
#
if [ ! -s ${antispam_mysql_mycnf} ]; then 
    ${zmail_home}/libexec/zmantispammycnf > ${antispam_mysql_mycnf}
fi

#
# Create database
#
echo '*' Creating database in ${antispam_mysql_data_directory}
(cd ${antispam_mysql_directory}; ./scripts/mysql_install_db \
    --basedir=${antispam_mysql_directory} \
    --datadir=${antispam_mysql_data_directory} \
    --defaults-file=${antispam_mysql_mycnf} ) \
    >> ${zmail_log_directory}/zmantispamdbinit.log 2>&1

#
# Start mysql server for antispam db
#
#echo '*' Starting antispam mysql server
#${zmail_home}/bin/antispam-mysql.server start \
#    >> ${zmail_log_directory}/antispam-mysql.log 2>&1
#sleep 30
zmassert -d `dirname ${antispam_mysql_pidfile}`
if [ -f ${antispam_mysql_pidfile} ]; then
    pid=`cat ${antispam_mysql_pidfile}`
fi
if [ "x$pid" != "x" ]; then
    kill -0 $pid 2> /dev/null
    if [ $? = 0 ]; then
        # What the heck happened here.  mysqld_safe for anti-spam should not already be running!
        echo "mysqld_safe for anti-spam already running with pid $pid"
        exit 1
    fi
fi
# --defaults-file must be first argument
echo -n '*' Starting antispam mysql server ...
cd ${antispam_mysql_directory}; \
${antispam_mysql_directory}/bin/mysqld_safe \
    --defaults-file=${antispam_mysql_mycnf} \
    --basedir=${antispam_mysql_directory} \
    --datadir=${antispam_mysql_data_directory} \
    --external-locking \
    --log-error=${antispam_mysql_errlogfile} \
    --ledir=${antispam_mysql_directory}/bin < /dev/null > /dev/null 2>&1 &
SQLSTARTED=0
for ((i = 0; i < 60; i++))
do
    ${zmail_home}/bin/antispam-mysqladmin -s ping 2>&1 > /dev/null
    if [ $? = 0 ]; then
        SQLSTARTED=1
        break
    fi
    sleep 2
done
if [ ${SQLSTARTED} -ne 1 ]; then
    echo "failed."
	exit 1
else
    echo "done."
fi


#
# Load zmail sql files
#
echo '*' Loading schema ${zmail_home}/data/amavisd/mysql/antispamdb.sql 
${zmail_home}/bin/antispam-mysql -u root --password= < \
    ${zmail_home}/data/amavisd/mysql/antispamdb.sql


#
# Generate passwords for mysql into local config
#
if [ x$sql_root_pw = "x" ]; then
    echo '*' Setting random password for antispam mysql root user in zmail local config
    ${zmail_home}/bin/zmlocalconfig -r -f -e antispam_mysql_root_password

    echo '*' Setting random password for antispam mysql zmail user in zmail local config
    ${zmail_home}/bin/zmlocalconfig -r -f -e antispam_mysql_password
else
    echo '*' Setting password for antispam mysql root user in zmail local config
    ${zmail_home}/bin/zmlocalconfig -f -e antispam_mysql_root_password=$sql_root_pw
    echo '*' Setting password for antispam mysql zmail user in zmail local config
    ${zmail_home}/bin/zmlocalconfig -f -e antispam_mysql_password=$sql_root_pw
fi

#
# Change mysql root user password, but first read back the passwords 
# zmail local config - they was generated above.  Note that we can not
# use 'zmmypasswd --root' here because of bootstrapping problems - at
# this stage we know that the root password is empty.
#
zmsetvars -f antispam_mysql_root_password antispam_mysql_password
echo '*' Changing antispam mysql root user password
${zmail_home}/bin/antispam-mysqladmin -u root --password= password ${antispam_mysql_root_password}

echo '*' Changing antispam mysql user password
${zmail_home}/bin/zmantispamdbpasswd ${antispam_mysql_password}
