#!/bin/bash 
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
# This may not be there, but we don't want to break the zmailmta package
# if it's installed.
shopt -s nullglob

root_user=root
zmail_home=/opt/zmail

PLAT=`/bin/sh ${zmail_home}/libexec/get_plat_tag.sh`
if [ "X$PLAT" = "XMACOSX" -o "X$PLAT" = "XMACOSXx86" ]; then
  root_group=wheel
else 
  root_group=root
fi

if [ "X$PLAT" = "XMACOSXx86_10.5" -o "X$PLAT" = "XMACOSXx86_10.6" -o "X$PLAT" = "XMACOSXx86_10.7" ]; then
  root_group=wheel
  postfix_owner=_postfix
  postfix_suid_group=_postdrop
else
  postfix_owner=postfix
  postfix_suid_group=postdrop
fi

if [ "X$PLAT" = "XUBUNTU10_64" -o "X$PLAT" = "XUBUNTU12_64" ]; then
  syslog_user=syslog
  syslog_group=adm
else
  syslog_user=zmail
  syslog_group=zmail
fi

zmail_user=zmail
zmail_group=zmail

extended=no
verbose=no

components="\
  amavisd \
  aspell \
  bdb \
  cbpolicyd \
  clamav \
  curl \
  cyrus-sasl \
  altermime \
  dspam \
  heimdal \
  httpd \
  keyview \
  libtool \
  memcached \
  mysql \
  net-snmp \
  nginx \
  openldap \
  openldap-clibs \
  openssl \
  perdition \
  rsync \
  snmp \
  tcmalloc \
  zmailmon/bin \
  zmailmon/crontabs \
  zmailmon/rrdtool \
  zmailmon/pylibs \
"
  

usage() {
  echo "$0 [-help] [-extended] [-verbose]"
  echo "-help     Usage"
  echo "-verbose  Verbose output"
  echo "-extended Extended fix, includes store,index,backup directories"
  echo "          * Using extended option can take a signifcant amount of time."
  echo 
  exit
}

for opt in "$@"; do
  case "$opt" in
    -verbose|--verbose|-v)
      verbose=yes
      shift
      ;;
    -help|--help|-h|--h)
      usage
      shift
      ;;
    -extended|--extended|-e)
      extended=yes 
      shift
      ;;
    *)
      echo "Unknown option $opt"
      usage
      shift
      ;;
  esac
done

printMsg() {
  if [ $verbose = "yes" ]; then
    echo $*
  fi
}

# NOT ${zmail_home}/{store,backup,index}
if [ ${extended} = "yes" ]; then
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/a* ${zmail_home}/[c-hj-ot-z]* ${zmail_home}/s[a-su-z]* 2> /dev/null
fi

if [ -d ${zmail_home} ]; then
  chown ${root_user}:${root_group} ${zmail_home}
  chmod 755 ${zmail_home}

  if [ -f ${zmail_home}/.viminfo ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/.viminfo
  fi

  if [ -f ${zmail_home}/.ldaprc ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/.ldaprc
  fi

  if [ -f ${zmail_home}/.exrc ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/.exrc
  fi

  if [ -f ${zmail_home}/.bash_profile ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/.bash_profile
  fi

  if [ -f ${zmail_home}/.bashrc ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/.bashrc
  fi

  if [ -f ${zmail_home}/.platform ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/.platform
  fi

  for i in .zmmailbox_history .zmprov_history .bash_history; do
    if [ ! -f ${zmail_home}/${i} ]; then
      touch ${zmail_home}/${i}
    fi
    chown ${zmail_user}:${zmail_group} ${zmail_home}/${i}
    chmod 640 ${zmail_home}/${i}
  done

  if [ -f /selinux/enforce ]; then
    if [ "`cat /selinux/enforce 2> /dev/null`" = "1" ]; then
      # make sure ssh keys are in home dir selinux type
      chcon -R -v -u system_u -t user_home_t ${zmail_home}/.ssh/
      if [ -f ${zmail_home}/httpd/modules/libphp5.so ]; then
        # allow text relocation for these problem files
        chcon -t textrel_shlib_t ${zmail_home}/httpd/modules/libphp5.so
      fi
      # Fix Zmail upgrades selinux perms
      restorecon -R /etc/security
    fi
  fi

  if [ -d ${zmail_home}/contrib ]; then
    chown -R ${root_user}:${root_group} ${zmail_home}/contrib
    chmod 755 ${zmail_home}/contrib/* 2> /dev/null
  fi

  if [ -d ${zmail_home}/libexec ]; then
    chown -R ${root_user}:${root_group} ${zmail_home}/libexec
    chmod 755 ${zmail_home}/libexec/* 2> /dev/null
  fi

  if [ -d ${zmail_home}/log ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/log
    if [ -f ${zmail_home}/log/.hotspot_compiler ]; then
      chown ${root_user}:${root_group} ${zmail_home}/log/.hotspot_compiler
      chmod 444 ${zmail_home}/log/.hotspot_compiler
    fi
  fi

  if [ -d ${zmail_home}/logger ]; then
    chown -R ${zmail_user}:${zmail_group} ${zmail_home}/logger 2> /dev/null
    chmod 755 ${zmail_home}/logger/* 2> /dev/null
  fi

  if [ -d ${zmail_home}/bin ]; then
    chown -R ${root_user}:${root_group} ${zmail_home}/bin
    chmod 755 ${zmail_home}/bin/* 2> /dev/null
  fi

  if [ -d ${zmail_home}/lib ]; then
    chown -R ${root_user}:${root_group} ${zmail_home}/lib
  fi

  if [ -d ${zmail_home}/wiki ]; then
    chown -R ${zmail_user}:${zmail_group} ${zmail_home}/wiki
  fi

  if [ -d ${zmail_home}/convertd ]; then
    chown -R ${zmail_user}:${zmail_group} ${zmail_home}/convertd
    chmod 755 ${zmail_home}/convertd
    if [ -d ${zmail_home}/convertd/bin ]; then
      chown -R ${root_user}:${root_group} ${zmail_home}/convertd/bin
      chmod 755 ${zmail_home}/convertd/bin
    fi
    if [ -d ${zmail_home}/convertd/lib ]; then
      chown -R ${root_user}:${root_group} ${zmail_home}/convertd/lib
      chmod 755 ${zmail_home}/convertd/lib
    fi
    if [ ! -d ${zmail_home}/convertd/convert ]; then
      mkdir -p ${zmail_home}/convertd/convert
      chown ${zmail_user}:${zmail_group} ${zmail_home}/convertd/convert
      chmod 700 ${zmail_home}/convertd/convert
    fi
  fi

  if [ -d ${zmail_home}/conf ]; then
    printMsg "Fixing ownership and permissions on ${zmail_home}/conf"
    chown -R ${zmail_user}:${zmail_group} ${zmail_home}/conf

    if [ -f ${zmail_home}/conf/ZCSLicense.xml ]; then
      chown ${zmail_user}:${zmail_group} ${zmail_home}/conf/ZCSLicense.xml
      chmod 440 ${zmail_home}/conf/ZCSLicense.xml
    fi

    if [ -f ${zmail_home}/conf/localconfig.xml ]; then
      chown ${zmail_user}:${zmail_group} ${zmail_home}/conf/localconfig.xml
      chmod 640 ${zmail_home}/conf/localconfig.xml
    fi

    if [ -d ${zmail_home}/conf/spamassassin ]; then
      printMsg "Fixing permissions on ${zmail_home}/conf/spamassassin"
      chmod 755 ${zmail_home}/conf/spamassassin
    fi

    if [ -f ${zmail_home}/conf/nginx.conf ]; then
      chown ${zmail_user}:${zmail_group} ${zmail_home}/conf/nginx.conf
      chmod 644 ${zmail_home}/conf/nginx.conf
    fi

    for i in ${zmail_home}/conf/*-{scm,transport,vad,vam,vmd,vmm}.cf; do
      printMsg "Fixing ownership and permissions on ${i}"
      chgrp -f ${postfix_owner} ${i}
      chmod 640 ${i}
    done 

    if [ -f ${zmail_home}/conf/my.cnf ]; then
      chown ${zmail_user}:${zmail_group} ${zmail_home}/conf/my.cnf
      chmod 640 ${zmail_home}/conf/my.cnf
    fi

    if [ -f ${zmail_home}/conf/saslauthd.conf.in ]; then
      chmod 640 ${zmail_home}/conf/saslauthd.conf.in
      chown ${zmail_user}:${zmail_group} ${zmail_home}/conf/saslauthd.conf.in
    fi
    if [ -f ${zmail_home}/conf/saslauthd.conf ]; then
      chmod 440 ${zmail_home}/conf/saslauthd.conf
      chown ${zmail_user}:${zmail_group} ${zmail_home}/conf/saslauthd.conf
    fi
    if [ -f ${zmail_home}/conf/sasl2/smtpd.conf.in ]; then
      chmod 640 ${zmail_home}/conf/sasl2/smtpd.conf.in
      chown ${zmail_user}:${zmail_group} ${zmail_home}/conf/sasl2/smtpd.conf.in
    fi
    if [ -f ${zmail_home}/conf/sasl2/smtpd.conf ]; then
      chmod 640 ${zmail_home}/conf/sasl2/smtpd.conf
      chown ${zmail_user}:${zmail_group} ${zmail_home}/conf/sasl2/smtpd.conf
    fi
  fi

  if [ -d ${zmail_home}/docs ]; then
    chown -R ${zmail_user}:${zmail_group} ${zmail_home}/docs
    find ${zmail_home}/docs -type d -exec chmod 755 {} \;
    find ${zmail_home}/docs -type f -exec chmod 444 {} \;
  fi

  for i in ${zmail_home}/zimlets*; do
    chown -R ${zmail_user}:${zmail_group} ${i}
  done

  for i in ${zmail_home}/conf/*.key; do
    printMsg "Fixing permissions and ownership on ${i}"
    chown ${zmail_user}:${zmail_group} $i
    chmod 640 $i
  done

  if [ ! -d ${zmail_home}/data ]; then
    mkdir -p ${zmail_home}/data
  fi
  chmod 755 ${zmail_home}/data
  chown ${zmail_user}:${zmail_group} ${zmail_home}/data

  if [ -d ${zmail_home}/extensions-network-extra ]; then
    chmod 755 ${zmail_home}/extensions-network-extra
    chown -R ${zmail_user}:${zmail_group} ${zmail_home}/extensions-network-extra
  fi

  if [ -d ${zmail_home}/extensions-extra ]; then
    chmod 755 ${zmail_home}/extensions-extra
    chown -R ${zmail_user}:${zmail_group} ${zmail_home}/extensions-extra
  fi

fi

# fix the temp directory
if [ ! -d ${zmail_home}/data/tmp ]; then
  mkdir -p ${zmail_home}/data/tmp
fi
# Handle nginx path problems bug#42156
if [ ! -d ${zmail_home}/data/tmp/nginx ]; then
  mkdir -p ${zmail_home}/data/tmp/nginx/client
  mkdir -p ${zmail_home}/data/tmp/nginx/proxy
  mkdir -p ${zmail_home}/data/tmp/nginx/fastcgi
fi
chown -R ${zmail_user}:${zmail_group} ${zmail_home}/data/tmp
chmod 1777 ${zmail_home}/data/tmp
chmod 755 ${zmail_home}/data/tmp/nginx
chmod 755 ${zmail_home}/data/tmp/nginx/client
chmod 755 ${zmail_home}/data/tmp/nginx/proxy
chmod 755 ${zmail_home}/data/tmp/nginx/fastcgi

if [ -f ${zmail_home}/.install_history ]; then
  chmod 644 ${zmail_home}/.install_history
fi

if [ -d /var/log/ ]; then
  printMsg "Fixing ownership and permissions on /var/log/zmail.log"
  if [ ! -f /var/log/zmail.log ]; then
    touch /var/log/zmail.log
  fi
  chown ${syslog_user}:${syslog_group} /var/log/zmail.log
  chmod 644 /var/log/zmail.log
fi

for i in ${components}; do
  if [ -L ${zmail_home}/${i} ]; then
    printMsg "Fixing ownership and permissions on ${zmail_home}/${i}"
    for l in ${zmail_home}/${i}-*; do
      chown ${root_user}:${root_group} ${l} 2> /dev/null
    done
    for l in ${zmail_home}/${i}/* ${zmail_home}/${i}/.???*; do
      chown -R ${root_user}:${root_group} ${l} 2> /dev/null
    done
  elif [ -d ${zmail_home}/${i} ]; then
    printMsg "Fixing ownership and permissions on ${zmail_home}/${i}"
    chown -R ${root_user}:${root_group} ${zmail_home}/${i} 2> /dev/null
    if [ x$i = "xzmailmon/pylibs" ]; then
      chmod a+r ${zmail_home}/${i}/*.class 2>/dev/null
    fi
  fi
done

for i in ${zmail_home}/jdk*; do
  printMsg "Fixing ownership and permissions on ${i}"
  chown -R ${root_user}:${root_group} ${i}
  chmod 755 ${i}
done

if [ -d ${zmail_home}/lib ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/lib"
  for i in ${zmail_home}/lib/lib*so*; do
    chown ${root_user}:${root_group} $i
    chmod 755 $i
  done
  if [ -d ${zmail_home}/lib/jars ]; then
    for i in ${zmail_home}/lib/jars/*; do
      chown ${root_user}:${root_group} $i
      chmod 444 $i
    done
  fi
 
  if [ -d ${zmail_home}/lib/ext ]; then
    find ${zmail_home}/lib/ext -type f -exec chown ${root_user}:${root_group} {} \;
    find ${zmail_home}/lib/ext -type f -exec chmod 444 {} \;
  fi
  if [ -d ${zmail_home}/lib/ext-common ]; then
    find ${zmail_home}/lib/ext-common -type f -exec chown ${root_user}:${root_group} {} \;
    find ${zmail_home}/lib/ext-common -type f -exec chmod 444 {} \;
  fi
fi
   
if [ -d ${zmail_home}/db ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/db"
  if [ ! -d ${zmail_home}/db/data ]; then
    mkdir -p ${zmail_home}/db/data
  fi
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/db
  chmod 444 ${zmail_home}/db/*.sql ${zmail_home}/db/*.sql.in
fi

if [ -L ${zmail_home}/cbpolicyd ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/cbpolicyd"
  chown -fR ${root_user}:${root_group} ${zmail_home}/cbpolicyd*
  if [ -d ${zmail_home}/cbpolicyd/bin ]; then
    for i in ${zmail_home}/cbpolicyd/bin/* ${zmail_home}/cbpolicyd/share/database/*tsql; do
      chmod 755 ${i}
    done
  fi
    
  for i in data/cbpolicyd data/cbpolicyd/db; do
    if [ ! -d "${zmail_home}/${i}" ]; then
      mkdir -p ${zmail_home}/${i}
    fi
  done
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/data/cbpolicyd
fi

if [ -d ${zmail_home}/mta ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/mta"
  chown -R ${root_user}:${root_group} ${zmail_home}/mta
  chmod 755 ${zmail_home}/mta
fi

if [ -L ${zmail_home}/cyrus-sasl ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/data/sasl2/state"
  if [ ! -d ${zmail_home}/data/sasl2/state ]; then  
    mkdir -p ${zmail_home}/data/sasl2/state
  fi
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/data/sasl2/state
  chmod 755 ${zmail_home}/data/sasl2/state 
fi

if [ -L ${zmail_home}/dspam ]; then
  if [ ! -d "${zmail_home}/data/dspam" ]; then
    mkdir -p ${zmail_home}/data/dspam
  fi
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/data/dspam
fi

if [ -L ${zmail_home}/altermime ]; then
  if [ ! -d "${zmail_home}/data/altermime" ]; then
    mkdir -p ${zmail_home}/data/altermime
  fi
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/data/altermime
fi

if [ -L ${zmail_home}/amavisd ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/data/amavisd"
  if [ ! -d "${zmail_home}/data/amavisd" ]; then
    mkdir -p ${zmail_home}/data/amavisd/.spamassassin
  fi
  if [ ! -d "/var/spamassassin" ]; then
    mkdir -p /var/spamassassin
    chown -R ${zmail_user}:${zmail_group} /var/spamassassin
  fi
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/data/amavisd
  if [ -d ${zmail_home}/amavisd/.spamassassin ]; then
    chown -R ${root_user}:${root_group} ${zmail_home}/amavisd/.spamassassin
  fi
fi


if [ -L ${zmail_home}/jetty ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/jetty"
  chown  ${root_user}:${root_group} /opt/zmail/jetty-* 2> /dev/null
  if [ -f ${zmail_home}/jetty/etc/keystore ]; then
    chmod 444 ${zmail_home}/jetty/etc/keystore
    chown ${zmail_user}:${zmail_group} ${zmail_home}/jetty/etc/keystore
  fi
  if [ -f ${zmail_home}/jetty/webapps/zmailAdmin/tmp/current.csr ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/jetty/webapps/zmailAdmin/tmp/current.csr
    chmod 444 ${zmail_home}/jetty/webapps/zmailAdmin/tmp/current.csr
  fi
  if [ -f ${zmail_home}/jetty/etc/jetty.xml.in ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/jetty/etc/jetty.xml.in
    chmod 640 ${zmail_home}/jetty/etc/jetty.xml.in
  fi
  if [ -f ${zmail_home}/jetty/etc/jetty.xml ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/jetty/etc/jetty.xml
    chmod 640 ${zmail_home}/jetty/etc/jetty.xml
  fi
  if [ -f ${zmail_home}/jetty/etc/service.web.xml.in ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/jetty/etc/service.web.xml.in
    chmod 640 ${zmail_home}/jetty/etc/service.web.xml.in
  fi
  if [ -f ${zmail_home}/jetty/etc/zmail.web.xml.in ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/jetty/etc/zmail.web.xml.in
    chmod 640 ${zmail_home}/jetty/etc/zmail.web.xml.in
  fi
  if [ -f ${zmail_home}/jetty/etc/zmailAdmin.web.xml.in ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/jetty/etc/zmailAdmin.web.xml.in
    chmod 640 ${zmail_home}/jetty/etc/zmailAdmin.web.xml.in
  fi
  if [ -f ${zmail_home}/jetty/etc/zimlet.web.xml.in ]; then
    chown ${zmail_user}:${zmail_group} ${zmail_home}/jetty/etc/zimlet.web.xml.in
    chmod 640 ${zmail_home}/jetty/etc/zimlet.web.xml.in
  fi

  if [ ! -d ${zmail_home}/jetty/webapps/zimlet/WEB-INF ]; then
    mkdir -p ${zmail_home}/jetty/webapps/zimlet/WEB-INF
  fi
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/jetty/webapps/zimlet
  chmod 755 ${zmail_home}/jetty/webapps/zimlet ${zmail_home}/jetty/webapps/zimlet/WEB-INF

  if [ ! -d ${zmail_home}/jetty/work/zimlet ]; then
    mkdir -p ${zmail_home}/jetty/work/zimlet
  fi
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/jetty/work/zimlet
  chmod 750 ${zmail_home}/jetty/work/zimlet

  if [ ! -d ${zmail_home}/jetty/work/spnego ]; then
    mkdir -p ${zmail_home}/jetty/work/spnego
  fi
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/jetty/work/spnego
  chmod 750 ${zmail_home}/jetty/work/spnego

  if [ ! -d ${zmail_home}/fbqueue ]; then
    mkdir -p ${zmail_home}/fbqueue
  fi
  chown ${zmail_user}:${zmail_group} ${zmail_home}/fbqueue
  chmod 755 ${zmail_home}/fbqueue

  if [ ! -d ${zmail_home}/zimlets-deployed ]; then
    mkdir -p ${zmail_home}/zimlets-deployed
  fi
  chown ${zmail_user}:${zmail_group} ${zmail_home}/zimlets-deployed
  chmod 755 ${zmail_home}/zimlets-deployed

  for i in ${zmail_home}/jetty/*; do
    chown -R ${zmail_user}:${zmail_group} ${i}
  done

  if [ -d ${zmail_home}/jetty/lib ]; then
    find ${zmail_home}/jetty/lib -type f -name '*.jar' -exec chown ${root_user}:${root_group} {} \; -exec chmod 444 {} \;
    find ${zmail_home}/jetty/lib -type d -exec chown ${root_user}:${root_group} {} \; -exec chmod 755 {} \;
  fi

  if [ -d ${zmail_home}/jetty/common ]; then
    find ${zmail_home}/jetty/common -type d -exec chown ${root_user}:${root_group} {} \; -exec chmod 755 {} \;
  fi  

  if [ ! -d ${zmail_home}/data/mailboxd ]; then
    mkdir -p ${zmail_home}/data/mailboxd
  fi
  chown ${zmail_user}:${zmail_group} ${zmail_home}/data/mailboxd
  chmod 755 ${zmail_home}/data/mailboxd

  if [ ! -d ${zmail_home}/data/mailboxd/spnego ]; then
    mkdir -p ${zmail_home}/data/mailboxd/spnego
  fi
  chown ${zmail_user}:${zmail_group} ${zmail_home}/data/mailboxd/spnego
  chmod 755 ${zmail_home}/data/mailboxd/spnego

fi

if [ -d ${zmail_home}/ssl ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/ssl"
  find ${zmail_home}/ssl -type f -exec chown ${root_user}:${root_group} {} \;
  find ${zmail_home}/ssl -type f -exec chmod 640 {} \;
fi

if [ -L ${zmail_home}/openldap ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/openldap"
  chown ${root_user}:${root_group} ${zmail_home}/openldap-* 2> /dev/null
  if [ -d ${zmail_home}/data/ldap ]; then
    chown -R ${zmail_user}:${zmail_group} ${zmail_home}/data/ldap
    chown ${zmail_user}:${zmail_group} ${zmail_home}/data/ldap
  fi
  if [ -e ${zmail_home}/openldap ]; then
    chown -R ${root_user}:${root_group} ${zmail_home}/openldap/* 2> /dev/null
    if [ -d ${zmail_home}/openldap/etc ]; then
      chown -R ${zmail_user}:${zmail_group} ${zmail_home}/openldap/etc
    fi
    if [ -d ${zmail_home}/openldap/var ]; then
      chown -R ${zmail_user}:${zmail_group} ${zmail_home}/openldap/var
    fi
    if [ -d ${zmail_home}/openldap/sbin ]; then
      for i in ${zmail_home}/openldap/sbin/*; do
        chmod 755 ${i}
      done
    fi
  fi
fi

if [ -d ${zmail_home}/snmp/var ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/snmp/var"
  chown ${zmail_user}:${zmail_group} ${zmail_home}/snmp/var
fi

if [ -d ${zmail_home}/logger/db ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/logger/db"
  chown ${zmail_user}:${zmail_group} ${zmail_home}/logger/db
  if [ ! -d ${zmail_home}/logger/db/data ]; then
    mkdir -p ${zmail_home}/logger/db/data
  fi
  chown ${zmail_user}:${zmail_group} ${zmail_home}/logger/db/data
fi

if [ -d ${zmail_home}/clamav/db ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/clamav/db"
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/clamav/db
fi

if [ -d ${zmail_home}/data/clamav ]; then
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/data/clamav
fi

if [ -L ${zmail_home}/tomcat ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/tomcat"
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/apache-tomcat-* 2> /dev/null
  chown  ${root_user}:${root_group} ${zmail_home}/apache-tomcat-* 2> /dev/null
  if [ -d ${zmail_home}/tomcat/bin ]; then
    chown -R ${root_user}:${root_group} ${zmail_home}/tomcat/bin
    if [ ! -d ${zmail_home}/tomcat/conf ]; then
      mkdir -p ${zmail_home}/tomcat/conf
      chown ${zmail_user}:${zmail_group} ${zmail_home}/tomcat/conf
    fi
  fi
fi

if [ -d ${zmail_home}/zmstat ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/zmstat"
  for i in ${zmail_home}/zmstat/????-??-??; do
    chown -R ${zmail_user}:${zmail_group} ${i}
  done
fi

if [ -d ${zmail_home}/zmailmon/lib ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/zmailmon/lib"
  chown ${root_user}:${root_group} ${zmail_home}/zmailmon
  chown -R ${root_user}:${root_group} ${zmail_home}/zmailmon/lib
fi

if [ -L ${zmail_home}/libmemcached ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/libmemcached"
  chown -fR ${root_user}:${root_group} ${zmail_home}/libmemcached*
fi

if [ -L ${zmail_home}/opendkim ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/opendkim"
  chown -fR ${root_user}:${root_group} ${zmail_home}/opendkim*
  if [ -d ${zmail_home}/data/opendkim ]; then
    chown -R ${zmail_user}:${zmail_group} ${zmail_home}/data/opendkim
  fi
fi

if [ -L ${zmail_home}/zeromq ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/zeromq"
  chown -fR ${root_user}:${root_group} ${zmail_home}/zeromq*
fi

if [ -L ${zmail_home}/postfix ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/postfix"
  chown -fR ${root_user}:${root_group} ${zmail_home}/postfix* 2> /dev/null

  if [ -e ${zmail_home}/postfix/conf ]; then
    if [ ! -f ${zmail_home}/postfix/conf/main.cf ]; then
      touch ${zmail_home}/postfix/conf/main.cf
    fi

    chown -fR ${root_user}:${postfix_owner} ${zmail_home}/postfix/conf
    chmod 775 ${zmail_home}/postfix/conf

    chmod -fR 644 ${zmail_home}/postfix/conf/* 2> /dev/null
    if [ -f ${zmail_home}/postfix/conf/postfix-script ]; then
      chmod -f 755 ${zmail_home}/postfix/conf/postfix-script
    fi
    if [ -f ${zmail_home}/postfix/conf/post-install ]; then
      chmod -f 755 ${zmail_home}/postfix/conf/post-install
    fi
    if [ -f ${zmail_home}/postfix/conf/master.cf.in ]; then
      chown -f ${zmail_user}:${zmail_group} ${zmail_home}/postfix/conf/master.cf.in
    fi
  fi

  # Postfix specific permissions
  if [ -d ${zmail_home}/postfix/sbin ]; then
    chgrp -f ${postfix_suid_group} ${zmail_home}/postfix/sbin/postqueue
    chgrp -f ${postfix_suid_group} ${zmail_home}/postfix/sbin/postdrop
    chmod -f g+s ${zmail_home}/postfix/sbin/postqueue
    chmod -f g+s ${zmail_home}/postfix/sbin/postdrop
  fi
  if [ ! -d ${zmail_home}/conf/sa ]; then
    mkdir -p ${zmail_home}/conf/sa
    chown -f ${zmail_user}:${zmail_group} ${zmail_home}/conf/sa
  fi
fi

if [ -d ${zmail_home}/data/postfix ]; then
  printMsg "Fixing ownership and permissions on ${zmail_home}/data/postfix"
  if [ ! -d ${zmail_home}/data/postfix/data ]; then
    mkdir -p ${zmail_home}/data/postfix/data
  fi
  if [ ! -d ${zmail_home}/data/postfix/spool/pid ]; then
    mkdir -p ${zmail_home}/data/postfix/spool/pid
  fi
  chmod 755 ${zmail_home}/data/postfix
  chown -fR ${postfix_owner}:${postfix_owner} ${zmail_home}/data/postfix/spool
  chown -f ${root_user} ${zmail_home}/data/postfix/spool
  chown -f ${postfix_owner} ${zmail_home}/data/postfix/spool/pid
  chgrp -f ${root_group} ${zmail_home}/data/postfix/spool/pid
  # Postfix specific permissions
  if [ -d ${zmail_home}/data/postfix/spool/public ]; then
    chgrp -f ${postfix_suid_group} ${zmail_home}/data/postfix/spool/public
  fi
  if [ -d ${zmail_home}/data/postfix/spool/maildrop ]; then
    chmod 730 ${zmail_home}/data/postfix/spool/maildrop
    chgrp -f ${postfix_suid_group} ${zmail_home}/data/postfix/spool/maildrop
    chmod 730 ${zmail_home}/data/postfix/spool/maildrop
  fi
  chown -f ${postfix_owner} ${zmail_home}/data/postfix
  chown -f ${postfix_owner} ${zmail_home}/data/postfix/* 2> /dev/null
  chgrp -f ${postfix_suid_group} ${zmail_home}/data/postfix/data
  chown -f ${postfix_owner}:${postfix_owner} ${zmail_home}/data/postfix/data/* 2> /dev/null
  chown -f ${root_user} ${zmail_home}/data/postfix/spool
  chgrp -f ${root_group} ${zmail_home}/data/postfix/spool
fi

if [ -d ${zmail_home}/index -a ${extended} = "yes" ]; then
  printMsg "Fixing ownership of ${zmail_home}/index"
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/index
fi

if [ -d ${zmail_home}/backup -a ${extended} = "yes" ]; then
  printMsg "Fixing ownership of ${zmail_home}/backup"
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/backup
fi

if [ -d ${zmail_home}/redolog -a ${extended} = "yes" ]; then
  printMsg "Fixing ownership of ${zmail_home}/redolog"
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/redolog
fi

if [ -d ${zmail_home}/store -a ${extended} = "yes" ]; then
  printMsg "Fixing ownership of ${zmail_home}/store"
  chown -R ${zmail_user}:${zmail_group} ${zmail_home}/store
fi

if [ -f ${zmail_home}/libexec/ZmSetup.app/Contents/MacOS/ZmSetup ]; then
  chown ${root_user}:${root_group} ${zmail_home}/libexec/ZmSetup.app/Contents/MacOS/ZmSetup
  chmod 544 ${zmail_home}/libexec/ZmSetup.app/Contents/MacOS/ZmSetup
fi


exit 0

