#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2012 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

source `dirname $0`/../bin/zmshutil || exit 1
zmsetvars \
  zmail_ldap_password \
  ldap_url

LDAP_URL=`echo ${ldap_url} | awk '{ print $1 }'`

GSA_ID_LIST=`/opt/zmail/bin/ldapsearch -x -H ${LDAP_URL} -w ${zmail_ldap_password} -D uid=zmail,cn=admins,cn=zmail -b '' '(&(objectClass=zmailDomain)(zmailGalAccountId=*))' zmailGalAccountId | awk '{if ($1 ~ /^zmailGalAccountId:$/) { print $2 } }'`

MY_HOSTNAME=`zmhostname`
for ID in $GSA_ID_LIST
do
  GSA_MAIL_HOST=`/opt/zmail/bin/ldapsearch -x -H ${LDAP_URL} -w ${zmail_ldap_password} -D uid=zmail,cn=admins,cn=zmail -b '' '(&(objectClass=zmailAccount)(zmailId='${ID}'))' zmailMailHost | awk '{if ($1 ~ /^zmailMailHost:$/) { print $2 } }'`
  if [ "x${GSA_MAIL_HOST}" == "x${MY_HOSTNAME}" ]
  then
    zmgsautil trickleSync -i ${ID} -n InternalGAL
  fi
done
