#!/bin/bash
#
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2008, 2009, 2010, 2012 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
#; ***** END LICENSE BLOCK *****
# 

if [ x`whoami` != xzmail ]; then
    echo Error: must be run as zmail user
    exit 1
fi

zmail_home=/opt/zmail
zmail_java_home=${zmail_home}/java
jspc_src_dir=${zmail_home}/mailboxd/webapps/zmail
jspc_build_dir=${zmail_home}/mailboxd/work/zmail/jsp
jspc_class_path="${zmail_home}/jetty/lib:${zmail_home}/jetty/lib/jsp:${zmail_home}/jetty/lib/ext:${zmail_home}/jetty/lib/plus:${zmail_home}/jetty/lib/naming:/opt/zmail/lib/ext:${zmail_home}/jetty/common/lib:${zmail_home}/jetty/webapps/zmail/WEB-INF/lib"

extensions="backup clamscanner network zmail-license zmailhsm zmailsync"
ext_dir="/opt/zmail/lib/ext-common"
for i in $extensions; do
  if [ -d "/opt/zmail/lib/ext/$i" ]; then
   jspc_class_path="${jspc_class_path}:${ext_dir}/$i"
  fi
done

for i in `ls ${zmail_home}/jetty/lib/jsp/*.jar`; do
  if [ x"$class_path" = "x" ]; then
    class_path="$i"
  else 
    class_path="${class_path}:$i"
  fi
done

java_version=$(${zmail_java_home}/bin/java -version 2>&1 | grep "java version" | sed -e 's/"//g' | awk '{print $NF}' | awk -F_ '{print $1}')
if [ x"$java_version" = "x1.6.0" ]; then
  java_options="-XX:ErrorFile=${zmail_home}/log"
else
  java_options=""
fi

java_cmd="${zmail_java_home}/bin/java $java_options \
  -client -Xmx256m \
  -Dzmail.home=${zmail_home} \
  -Djava.library.path=${zmail_home}/lib \
  -Djava.ext.dirs=${jspc_class_path}"

if [ -d "${jspc_build_dir}" ]; then
  rm -rf ${jspc_build_dir}
fi
mkdir ${jspc_build_dir}

compile_jsp() {
  file=shift
  ${java_cmd} org.apache.jasper.JspC -v -d ${jspc_build_dir} -webapp ${jspc_src_dir} -uriroot ${jspc_src_dir} -compile -classpath ${class_path}
  return $?
}

compile_jsp ${param_jspfile}
if [ $? = 0 ]; then
  echo "done."
else
  echo "failed."
fi
