#!/bin/bash
#
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2008, 2009, 2010, 2011, 2012 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
#

source `dirname $0`/../bin/zmshutil || exit 1

zmsetvars -f zmail_home zmail_user

u=`id -un`
if [ $u != ${zmail_user} ]; then
  echo "Error: must be run as ${zmail_user} user"
  exit 1
fi

verifyLdapInstalled() {
  echo -n "Looking for LDAP installation..."
  if [ ! -d ${zmail_home}/openldap/etc/openldap/schema ]; then
    echo "FAILED"
    echo "ERROR: openldap does not appear to be installed - exiting"
    exit 1
  fi
  echo "succeeded"
}

createSchemaDir() {
  mkdir -p ${zmail_home}/data/ldap/config/cn\=config/cn\=schema
  chown ${zmail_user}:${zmail_user} ${zmail_home}/data/ldap/config/cn\=config/cn\=schema
  chmod 750 ${zmail_home}/data/ldap/config/cn\=config/cn\=schema
}

installCoreSchema() {
  echo "Installing core schema..."
  cp -f ${zmail_home}/openldap/etc/openldap/schema/core.ldif ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{0\}core.ldif
  chown ${zmail_user}:${zmail_user} ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{0\}core.ldif
  chmod 600 ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{0\}core.ldif
  sed -i.orig -e '/^dn: cn=core,/ s/dn: cn=core,cn=schema,cn=config/dn: cn={0}core/' -e '/^cn: core/ s/cn: core/cn: {0}core/' \
    ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{0\}core.ldif
}

installCosineSchema() {
  echo "Installing cosine schema..."
  cp -f ${zmail_home}/openldap/etc/openldap/schema/cosine.ldif ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{1\}cosine.ldif
  chown ${zmail_user}:${zmail_user} ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{1\}cosine.ldif
  chmod 600 ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{1\}cosine.ldif
  sed -i.orig -e '/^dn: cn=cosine,/ s/dn: cn=cosine,cn=schema,cn=config/dn: cn={1}cosine/' -e '/^cn: cosine/ s/cn: cosine/cn: {1}cosine/' \
    ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{1\}cosine.ldif
}

installInetOrgPersonSchema() {
  echo "Installing inetOrgPerson schema..."
  cp -f ${zmail_home}/openldap/etc/openldap/schema/inetorgperson.ldif ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{2\}inetorgperson.ldif
  chown ${zmail_user}:${zmail_user} ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{2\}inetorgperson.ldif
  chmod 600 ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{2\}inetorgperson.ldif
  sed -i.orig -e '/^dn: cn=inetorgperson,/ s/dn: cn=inetorgperson,cn=schema,cn=config/dn: cn={2}inetorgperson/' -e '/^cn: inetorgperson/ s/cn: inetorgperson/cn: {2}inetorgperson/' \
    ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{2\}inetorgperson.ldif
}

installZmailSchema() {
  echo "Installing zmail schema..."
  cp -f ${zmail_home}/openldap/etc/openldap/schema/zmail.ldif ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{4\}zmail.ldif
  chown ${zmail_user}:${zmail_user} ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{4\}zmail.ldif
  chmod 600 ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{4\}zmail.ldif
  sed -i.orig -e '/^dn: cn=zmail,/ s/dn: cn=zmail,cn=schema,cn=config/dn: cn={4}zmail/' -e '/^cn: zmail/ s/cn: zmail/cn: {4}zmail/' \
    ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{4\}zmail.ldif
}

installAmavisSchema() {
  echo "Installing amavis schema..."
  cp -f ${zmail_home}/openldap/etc/openldap/schema/amavisd.ldif ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{5\}amavisd.ldif
  chown ${zmail_user}:${zmail_user} ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{5\}amavisd.ldif
  chmod 600 ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{5\}amavisd.ldif
  sed -i.orig -e '/^dn: cn=amavisd,/ s/dn: cn=amavisd,cn=schema,cn=config/dn: cn={5}amavisd/' -e '/^cn: amavisd/ s/cn: amavisd/cn: {5}amavisd/' \
    ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{5\}amavisd.ldif
}

installDynlistSchema() {
  echo "Installing dyngroup schema..."
  cp -f ${zmail_home}/openldap/etc/openldap/schema/dyngroup.ldif ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{3\}dyngroup.ldif
  chown ${zmail_user}:${zmail_user} ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{3\}dyngroup.ldif
  chmod 600 ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{3\}dyngroup.ldif
  sed -i.orig -e '/^dn: cn=dyngroup,/ s/dn: cn=dyngroup,cn=schema,cn=config/dn: cn={3}dyngroup/' -e '/^cn: dyngroup/ s/cn: dyngroup/cn: {3}dyngroup/' \
    ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{3\}dyngroup.ldif
}

installOpenDKIMSchema() {
  echo "Installing OpenDKIM schema..."
  cp -f ${zmail_home}/openldap/etc/openldap/schema/opendkim.ldif ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{6\}opendkim.ldif
  chown ${zmail_user}:${zmail_user} ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{6\}opendkim.ldif
  chmod 600 ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{6\}opendkim.ldif
  sed -i.orig -e '/^dn: cn=opendkim,/ s/dn: cn=opendkim,cn=schema,cn=config/dn: cn={6}opendkim/' -e '/^cn: opendkim/ s/cn: opendkim/cn: {6}opendkim/' \
    ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/cn\=\{6\}opendkim.ldif
}

cleanup() {
  rm -f ${zmail_home}/data/ldap/config/cn\=config/cn\=schema/*.orig
}

verifyLdapInstalled
createSchemaDir
installCoreSchema
installCosineSchema
installInetOrgPersonSchema
installZmailSchema
installAmavisSchema
installDynlistSchema
installOpenDKIMSchema
cleanup
