#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

if [ x`whoami` != "xzmail" ]; then
  echo "Error: must be run as user zmail"
  exit 1
fi

usage() {
  echo "$0 [--help] [--sql_root_pw <password>] [--mysql_memory_percent 30]"
  echo "  --sql_root_pw defaults to random password if not specified."
  echo "  --mysql_memory_percent defaults to 30 percent if not specified."
}

source `dirname $0`/../bin/zmshutil || exit 1
zmsetvars -f

#
# Sanity checks
#
zmassert -x ${zmail_home}/libexec/zmmycnf
zmassert -x ${zmail_home}/bin/mysqladmin
zmassert -x ${zmail_home}/bin/mysql
zmassert -x ${zmail_home}/bin/zmlocalconfig
zmassert -x ${zmail_home}/bin/zmmypasswd
zmassert -x ${mysql_directory}/scripts/mysql_install_db
zmassert -r ${zmail_db_directory}/db.sql
zmassert -r ${zmail_db_directory}/versions-init.sql

for opt in "$@"; do
  case "$opt" in
    -help|--help|-h|--help)
      usage
      exit 0
      shift
      ;;
    -verbose|--verbose|-v|--v)
      verbose=yes
      shift
      ;;
    --sql_root_pw)
      shift
      sql_root_pw=$1
      shift
      ;;
    --mysql_memory_percent)
      shift
      mysql_memory_percent=$1
      shift
      ;;
    --*|-*)
      echo "Unknown option $opt"
      usage
      exit 1
      shift
      ;;
  esac
done

mysql_memory_percent=${mysql_memory_percent:=30}
if [ x"$verbose" = "xyes" ]; then
  echo "mysql_memory_percent=$mysql_memory_percent"
fi

#
# Create necessary directories
#
echo '*' Creating required directories
mkdir -p ${mysql_data_directory}
mkdir -p ${zmail_index_directory}
mkdir -p ${zmail_store_directory}
mkdir -p ${zmail_log_directory}

#
# Generate a mysql config file
#
echo '*' Generating mysql config ${mysql_mycnf}
rm -f ${mysql_mycnf}
${zmail_home}/libexec/zmmycnf --innodb-buffer-pool-memory-percent \
  $mysql_memory_percent > ${mysql_mycnf}

#
# Create database
#
echo '*' Creating database in ${mysql_data_directory}
(cd ${mysql_directory}; ./scripts/mysql_install_db \
    --defaults-file=${mysql_mycnf}) \
    >> ${zmail_log_directory}/zmmyinit.log 2>&1

#
# Start mysql server
#
echo '*' Starting mysql server
${zmail_home}/bin/mysql.server start \
    >> ${zmail_log_directory}/zmmyinit.log 2>&1

# make sure we can connect before continuing 
until `echo "show processlist" | ${zmail_home}/bin/mysql -u root --password= > /dev/null 2>&1`; do
  let i++
  sleep 5
  if [ $i -gt 25 ]; then
    echo '*' Failed to connect to mysql...giving up!
    exit -1
  else 
    echo '*' Failed to connect to mysql...retrying
  fi
done

#
# Load zmail sql files
#
echo '*' Loading schema ${zmail_db_directory}/db.sql 
${zmail_home}/bin/mysql -u root --password= < \
    ${zmail_db_directory}/db.sql

if [ -f "${zmail_db_directory}/create_sharing_database.sql" ];then
  echo '*' Loading schema ${zmail_db_directory}/create_sharing_database.sql 
  ${zmail_home}/bin/mysql -u root --password= < \
      ${zmail_db_directory}/create_sharing_database.sql
fi

echo '*' Loading version from ${zmail_db_directory}/versions-init.sql
${zmail_home}/bin/mysql -u root --password= < \
    ${zmail_db_directory}/versions-init.sql

if [ -f "${zmail_db_directory}/backup-version-init.sql" ]; then
  echo '*' Loading version from ${zmail_db_directory}/backup-version-init.sql
  ${zmail_home}/bin/mysql -u root --password= < \
    ${zmail_db_directory}/backup-version-init.sql
fi

#
# Delete wildcard user login entries
#
${zmail_home}/bin/mysql -u root --password= -e "DROP USER ''@'localhost'; DROP USER ''@'`hostname`';"

#
# Generate passwords for mysql into local config
#
if [ x$sql_root_pw = "x" ]; then
    echo '*' Setting random passwd for mysql root user in zmail localconfig
    ${zmail_home}/bin/zmlocalconfig -r -f -e mysql_root_password
    
    echo '*' Setting random passwd for mysql zmail user in zmail localconfig
    ${zmail_home}/bin/zmlocalconfig -r -f -e zmail_mysql_password
else
    echo '*' Setting passwd for mysql root user in zmail localconfig
    ${zmail_home}/bin/zmlocalconfig -f -e mysql_root_password=$sql_root_pw
    echo '*' Setting passwd for mysql zmail user in zmail localconfig
    ${zmail_home}/bin/zmlocalconfig -f -e zmail_mysql_password=$sql_root_pw
fi

#
# Change mysql root user password, but first read back the passwords 
# zmail local config - they was generated above.  Note that we can not
# use 'zmmypasswd --root' here because of bootstrapping problems - at
# this stage we know that the root password is empty.
#
zmsetvars -f mysql_root_password zmail_mysql_password
echo '*' Changing mysql root user password
cat <<EOF | ${zmail_home}/bin/mysql -u root --password=
    SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${mysql_root_password}');
    SET PASSWORD FOR 'root'@'`hostname`' = PASSWORD('${mysql_root_password}');
    SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('${mysql_root_password}');
    SET PASSWORD FOR 'root'@'::1' = PASSWORD('${mysql_root_password}');
    SET PASSWORD FOR 'root'@'localhost.localdomain' = PASSWORD('${mysql_root_password}');
EOF

echo '*' Changing mysql zmail user password
${zmail_home}/bin/zmmypasswd ${zmail_mysql_password}

