#!/usr/bin/perl
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
use strict;
use lib qw(/opt/zmail/zmailmon/lib /opt/zmail/libexec/scripts);
use Net::DNS;
use Socket;
use Net::LDAP;
use Net::LDAP::LDIF;
use Getopt::Long;
use File::Basename;


my (%c,%loaded,%saved,$rc);
my ($oldServerName, $newServerName, $help, $verbose, $force, $delete, $skipusers, $usersonly);

my (undef, undef,$uid,$gid) = getpwnam('zmail');
if ($> ne $uid) {
  print "Must be run as user zmail.\n";
  &usage
}

GetOptions("help" => \$help, 
    "oldservername=s" => \$oldServerName,
    "newservername=s" => \$newServerName,
    "force" => \$force,
    "deletelogger" => \$delete,
    "skipusers" => \$skipusers,
    "usersonly" => \$usersonly,
    "verbose+" => \$verbose);

&usage if ($help or !$newServerName);



$c{zmlocalconfig}="/opt/zmail/bin/zmlocalconfig";
$c{zmail_home} = getLocalConfig("zmail_home");
$c{zmprov}="$c{zmail_home}/bin/zmprov -l -m --";
$c{zmcertmgr}="$c{zmail_home}/bin/zmcertmgr";

if ($usersonly && !$oldServerName) {
  print "--usersonly requries --oldServerName.\n";
  exit 0;
}

if ($oldServerName) {
  $c{zmail_server_hostname} = $oldServerName;
} else {
  $c{zmail_server_hostname} = getLocalConfig("zmail_server_hostname");
}


if ($c{zmail_server_hostname} eq $newServerName) {
  print "Hostname is already $newServerName.\n";
  exit 0 unless $force;
}

if (!$force) {
  my $dns=1;
  my $res = Net::DNS::Resolver->new;
  my $answer = $res->search($newServerName);
  if (!defined($answer)) {
    print "Warning: Hostname $newServerName is not resolvable via DNS\n";
    $dns=0;
  }
  if (!$dns) {
    my @a=gethostbyname("$newServerName");
    my $iaddr=splice(@a,4);
    if (!defined($iaddr)) {
      print "Error: Hostname $newServerName is not resolvable via /etc/hosts or DNS.\n";
      exit 1;
    }
  }
}

$c{zmail_ldap_userdn} = getLocalConfig("zmail_ldap_userdn");
$c{zmail_ldap_password} = getLocalConfig("zmail_ldap_password");
$c{ldap_is_master} = getLocalConfig("ldap_is_master");
$c{ldap_url} = getLocalConfig("ldap_url");
$c{ldap_master_url} = getLocalConfig("ldap_master_url");
$c{ldap_starttls_supported} = getLocalConfig("ldap_starttls_supported");
my @masters=split(/ /, $c{ldap_master_url});
my $master_ref=\@masters;

&startLdap if (lc($c{ldap_is_master}) eq "true");
$c{zmail_log_host} = getLdapGlobalConfig("zmailLogHostname") if ($delete);

if ($delete && $c{zmail_log_host} eq "") {
  print "Unabled to determine zmail_log_host to delete.\n";
  exit 1;
}

# ***** Main *****

if (!$usersonly) {
  print "Renaming $c{zmail_server_hostname} to $newServerName\n";
  print "Shutting down zmail...";
  my $rc = runCommand("$c{zmail_home}/bin/zmcontrol stop");
  print (($rc==0) ? "done.\n" : "failed.\n");


  updateLocalConfig("ldap_master_url");
  updateLocalConfig("ldap_url");
  updateLocalConfig("ldap_host");
  updateLocalConfig("av_notify_user");
  updateLocalConfig("av_notify_domain");
  updateLocalConfig("snmp_trap_host");
  updateLocalConfig("smtp_source");
  updateLocalConfig("smtp_destination");
  updateLocalConfig("zmail_server_hostname");

  &startLdap if (lc($c{ldap_is_master}) eq "true");

  $c{zmailServiceEnabled} = getLdapServerConfig("zmailServiceEnabled");

  modifyServerName($newServerName);

  if (!$skipusers) {
    modifyAccountData($newServerName);
  }

  print "Services: $c{zmailServerEnabled}\n";
  # Reinitialize mta config
  if (index($c{zmailServiceEnabled}, "mta") != -1) {
    $c{ldap_host} = getLocalConfig("ldap_host");
    $c{ldap_port} = getLocalConfig("ldap_port");
    print "Reinitializing the mta config...";
    $rc = runCommand("$c{zmail_home}/libexec/zmmtainit $c{ldap_host} $c{ldap_port}");
    print (($rc==0) ? "done.\n" : "failed.\n");
  }

  # Reinitialize swatchrc
  if (index($c{zmailServiceEnabled}, "snmp") != -1) {
    print "Reinitializing the snmp config...";
    $rc = runCommand("$c{zmail_home}/libexec/zmsnmpinit");
    print (($rc==0) ? "done.\n" : "failed.\n");
  }

  #remap or delete logger data for the host
  if (index($c{zmailServiceEnabled}, "logger") != -1) {
    if ($delete) {
      runCommand("$c{zmail_home}/bin/zmloggerhostmap -d $oldServerName $oldServerName");
    } else {
      runCommand("$c{zmail_home}/bin/zmloggerhostmap $oldServerName $newServerName");
    }
  } else {
    if ($delete) {
      runCommand("$c{zmail_home}/libexec/zmrc $c{zmail_log_host} HOST:$c{zmail_log_host} zmloggerhostmap -d $oldServerName $oldServerName");
    } else {
      runCommand("$c{zmail_home}/libexec/zmrc $c{zmail_log_host} HOST:$c{zmail_log_host} zmloggerhostmap $oldServerName $newServerName");
    }
  }

  # Regenerate Self-signed certs
  if (!-f "$c{zmail_home}/ssl/zmail/commercial/commercial.crt") {
    if(lc($c{ldap_is_master}) eq "true") {
      runCommand("sudo $c{zmcertmgr} createca -new");
    }
    runCommand("sudo $c{zmcertmgr} createcrt self -new");
  }
} else {
  modifyAccountData($newServerName);
}


exit 0;
# ***** End Main *****

# ***** Subroutines *****
sub usage {
  print "\n";
  print "Usage: " . basename($0) . " [-h] [-d] [-f] [-s] [-o <oldServerName>] [-v+] -n <newServerName>\n";
  print "Changes the name of the local zmail server.\n";
  print " -h | --help                                 Print this usage statement.\n";
  print " -f | --force                                Force the rename, bypassing safety checks.\n";
  print " -o <oldServerName> | --oldServerName <oldServerName>\n";
  print "                                             Previous name for the server.  Defaults to LC zmail_server_hostname.\n";
  print " -n <newServerName> | --newServerName <newServerName>\n";
  print "                                             New name for the server.\n";
  print " -d | --deletelogger                         Delete the logger database for the old server.  Default is to remap\n";
  print "                                             its data to the new hostname.\n";
  print " -s | --skipusers                            Skips modifying the user database with the new server.\n"; 
  print " -u | --usersonly                            Only updates the user database.  This way, you can run once to do all\n";
  print "                                             the server updates, and then a second time to update the accounts.\n";
  print "                                             Likely requires --force.\n";
  print " -v | --verbose:                             Set the verbosity level.  Can be specified multiple times to increase\n";
  print "                                             the level.\n";
  print "\n";
  exit 0; 
}

sub modifyServerName($) {
  my ($server) = @_;
  my $config_base = "cn=config,cn=zmail";
  my $server_base = "cn=servers,cn=zmail";
  my $cos_base = "cn=cos,cn=zmail";
  my $zmail_base = "cn=zmail";
  my $root_base = "";
  my $ldap;
  unless($ldap = Net::LDAP->new($master_ref)) {
    print ("Unable to contact $c{ldap_master_url}: $!\n");
    return 1;
  }
  my $result;
  if ($c{ldap_master_url} !~ /^ldaps/i) {
    if ($c{ldap_starttls_supported}) {
      $result = $ldap->start_tls(
        verify => 'none',
        capath => "$c{zmail_home}/conf/ca",
        ) or die "start_tls: $@";
      $result->code && die "TLS: " . $result->error . "\n";
    }
  }
  $result = $ldap->bind($c{zmail_ldap_userdn}, 
    password => $c{zmail_ldap_password});
  if ($result->code()) {
    print("ldap bind failed for $c{zmail_ldap_userdn}\n");
    return 1;
  } else {
    print("ldap bind done for $c{zmail_ldap_userdn}\n") if ($verbose > 1);
    print "Searching for ldap server entry...";
    $result = $ldap->search(base => $server_base, 
      scope => 'one', 
      filter => "(cn=$c{zmail_server_hostname})");
    print ($result->code() ? "failed.\n" : "done.\n");
    return $result if ($result->code());

    # Rename server entry
    foreach my $entry ($result->all_entries) {
      print "Renaming ", $entry->dn(), "...";
      $result = $ldap->moddn(
        $entry->dn,
        newrdn=>"cn=$server",
        deleteoldrdn => 1
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailServiceHostname attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $server_base,
      scope =>'one',
      attrs => ['1.1'],
      filter => "(&(objectClass=zmailServer)(zmailServiceHostname=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailServiceHostname for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        replace => {zmailServiceHostname => "$server"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailMtaAuthHost attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $server_base,
      scope =>'one',
      attrs => ['cn'],
      filter => "(&(objectClass=zmailServer)(zmailMtaAuthHost=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailMtaAuthHost for ", $entry->dn(), "...";
      addLdapServerConfig($entry->get_value("cn"), "zmailMtaAuthHost", "$server");
      removeLdapServerConfig($entry->get_value("cn"), "zmailMtaAuthHost","$c{zmail_server_hostname}");
    }
    $result = $ldap->search(base => $config_base,
      scope =>'base',
      attrs => ['1.1'],
      filter => "(&(objectClass=zmailGlobalConfig)(zmailMtaAuthHost=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailMtaAuthHost for ", $entry->dn(), "...";
      addLdapGlobalConfig("zmailMtaAuthHost", "$server");
      removeGlobalConfig("zmailMtaAuthHost","$c{zmail_server_hostname}");
    }
    print("Updating zmailConvertdURL attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $zmail_base,
      scope =>'sub',
      attrs => ['zmailConvertdURL'],
      filter => "(&(|(objectClass=zmailServer)(objectClass=zmailGlobalConfig))(zmailConvertdURL=*://$c{zmail_server_hostname}:*))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailConvertdURL for ", $entry->dn(), "...";
      my $value=$entry->get_value("zmailConvertdURL");
      $value =~ s/$c{zmail_server_hostname}/$server/g;
      $result = $ldap->modify(
        $entry->dn,
        replace => {zmailConvertdURL => "$value"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailSpellCheckURL attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $zmail_base,
      scope =>'sub',
      attrs => ['zmailSpellCheckURL'],
      filter => "(&(|(objectClass=zmailServer)(objectClass=zmailGlobalConfig))(zmailSpellCheckURL=*://$c{zmail_server_hostname}:*))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailSpellCheckURL for ", $entry->dn(), "...";
      my @value=$entry->get_value("zmailSpellCheckURL");
      foreach my $val (@value) {
        if ($val =~ /$c{zmail_server_hostname}/) {
          my $new_val= $val;
          $new_val =~ s/$c{zmail_server_hostname}/$server/g;
          $result = $ldap->modify(
            $entry->dn,
            add => {zmailSpellCheckURL => "$new_val"},
            delete => {zmailSpellCheckURL => "$val"},
            );
          print ($result->code() ? "failed.\n" : "done.\n");
        }
      }
    }
    print("Updating zmailSmtpHostname attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $root_base,
      scope =>'sub',
      attrs => ['1.1'],
      filter => "(&(|(objectClass=zmailServer)(objectClass=zmailGlobalConfig)(objectClass=zmailDomain))(zmailSmtpHostname=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailSmtpHostname for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        add => {zmailSmtpHostname => "$server"},
        delete => {zmailSmtpHostname => "$c{zmail_server_hostname}"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailWebClientAdminReference attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $root_base,
      scope =>'sub',
      attrs => ['zmailWebClientAdminReference'],
      filter => "(&(|(objectClass=zmailDomain)(objectClass=zmailGlobalConfig))(zmailWebClientAdminReference=*://$c{zmail_server_hostname}:*))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailWebClientAdminReference for ", $entry->dn(), "...";
      my $value=$entry->get_value("zmailWebClientAdminReference");
      $value =~ s/$c{zmail_server_hostname}/$server/g;
      $result = $ldap->modify(
        $entry->dn,
        replace => {zmailWebClientAdminReference => "$value"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailVirtualHostname attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $root_base,
      scope =>'sub',
      attrs => ['zmailVirtualHostname'],
      filter => "(&(objectClass=zmailDomain)(zmailVirtualHostname=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailVirtualHostname for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        add => {zmailVirtualHostname => "$server"},
        delete => {zmailVirtualHostname => "$c{zmail_server_hostname}"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailDNSCheckHostname attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $root_base,
      scope =>'sub',
      attrs => ['1.1'],
      filter => "(&(|(objectClass=zmailDomain)(objectClass=zmailGlobalConfig))(zmailDNSCheckHostname=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailDNSCheckHostname for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        replace => {zmailDNSCheckHostname => "$server"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailDataSourceHost attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $root_base,
      scope =>'sub',
      attrs => ['1.1'],
      filter => "(&(objectClass=zmailDataSource)(zmailDataSourceHost=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailDataSourceHost for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        replace => {zmailDataSourceHost => "$server"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailMtaMyHostname attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $zmail_base,
      scope =>'sub',
      attrs => ['1.1'],
      filter => "(&(|(objectClass=zmailServer)(objectClass=zmailGlobalConfig))(zmailMtaMyHostname=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailMtaMyHostname for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        replace => {zmailMtaMyHostname => "$server"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailMtaRelayHost attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $zmail_base,
      scope =>'sub',
      attrs => ['1.1'],
      filter => "(&(|(objectClass=zmailServer)(objectClass=zmailGlobalConfig))(zmailMtaRelayHost=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailMtaRelayHost for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        add => {zmailMtaRelayHost => "$server"},
        delete => {zmailMtaRelayHost => "$c{zmail_server_hostname}"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailLogHostname attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $config_base,
      scope =>'sub',
      attrs => ['1.1'],
      filter => "(&(objectClass=zmailGlobalConfig)(zmailLogHostname=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailLogHostname for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        add => {zmailLogHostname => "$server"},
        delete => {zmailLogHostname => "$c{zmail_server_hostname}"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailPublicServiceHostname attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $root_base,
      scope =>'sub',
      attrs => ['1.1'],
      filter => "(&(|(objectClass=zmailDomain)(objectClass=zmailGlobalConfig))(zmailPublicServiceHostname=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailPublicServiceHostname for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        replace => {zmailPublicServiceHostname => "$server"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailServerHostPool attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $cos_base,
      scope =>'one',
      attrs => ['1.1'],
      filter => "(&(objectClass=zmailCOS)(zmailServerHostPool=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailServerHostPool for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        add => {zmailServerHostPool => "$server"},
        delete => {zmailServerHostPool => "$c{zmail_server_hostname}"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
  }
  $result = $ldap->unbind;
  return 0;
}

sub modifyAccountData($) {
  my ($server) = @_;
  my $ldap_base = "";
  my $ldap;
  unless($ldap = Net::LDAP->new($master_ref)) {
    print ("Unable to contact $c{ldap_master_url}: $!\n");
    return 1;
  }
  my $result;
  if ($c{ldap_master_url} !~ /^ldaps/i) {
    if ($c{ldap_starttls_supported}) {
      $result = $ldap->start_tls(
        verify => 'none',
        capath => "$c{zmail_home}/conf/ca",
        ) or die "start_tls: $@";
      $result->code && die "TLS: " . $result->error . "\n";
    }
  }
  $result = $ldap->bind($c{zmail_ldap_userdn}, 
    password => $c{zmail_ldap_password});
  if ($result->code()) {
    print("ldap bind failed for $c{zmail_ldap_userdn}");
    return 1;
  } else {
    print("ldap bind done for $c{zmail_ldap_userdn}\n") if ($verbose > 1);
    print("Updating zmailMailHost attributes\n") if ($verbose > 1);
    $result = $ldap->search(base => $ldap_base,
      scope =>'sub',
      attrs => ['1.1'],
      filter => "(&(objectClass=zmailAccount)(zmailMailHost=$c{zmail_server_hostname}))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailMailHost for ", $entry->dn(), "...";
      $result = $ldap->modify(
        $entry->dn,
        replace => {zmailMailHost => "$server"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
    print("Updating zmailMailTransport attribute\n") if ($verbose > 1);
    $result = $ldap->search(base => $ldap_base,
      scope =>'sub',
      attrs => ['zmailMailTransport'],
      filter => "(&(objectClass=zmailAccount)(zmailMailTransport=*:$c{zmail_server_hostname}:*))");
    return $result if ($result->code());
    foreach my $entry ($result->all_entries) {
      print "Updating zmailMailTransport for ", $entry->dn(), "...";
      my $value=$entry->get_value("zmailMailTransport");
      $value =~ s/$c{zmail_server_hostname}/$server/g;
      $result = $ldap->modify(
        $entry->dn,
        replace => {zmailMailTransport => "$value"},
        );
      print ($result->code() ? "failed.\n" : "done.\n");
    }
  }
  $result = $ldap->unbind;
  return 0;
}

sub updateLocalConfig($) {
  my ($key) = @_;
  my $tmpval = getLocalConfig($key);
  my $newval = $tmpval;
  $newval =~ s/$c{zmail_server_hostname}/$newServerName/g;
  return if ($tmpval eq $newval);
  my $rc = setLocalConfig($key, $newval) ;
  return $tmpval if ($rc==0);
}

sub getLocalConfig {
  my ($key,$force) = @_;

  return $loaded{lc}{$key}
    if (exists $loaded{lc}{$key} && !$force);
  print "Getting local config $key=";
  my $val = `$c{zmlocalconfig} -x -s -m nokey ${key} 2> /dev/null`;
  chomp $val;
  $loaded{lc}{$key} = $val;
  print "$val\n"; 
  return $val;
}

sub setLocalConfig {
  my $key = shift;
  my $val = shift;

  if (exists $saved{lc}{$key} && $saved{lc}{$key} eq $val) {
    return;
  }
  $saved{lc}{$key} = $val;
  $loaded{lc}{$key} = $val;
  print "Setting local config $key=$val\n";
  runCommand("$c{zmlocalconfig} -f -e ${key}=\'${val}\' 2> /dev/null");
}

sub setLdapServerConfig($$$) {
  my ($hn,$key,$val) = @_;
  return 
    if (exists $saved{gs}{$key} && $saved{gs}{$key} eq $val);
  if ($val eq "") {
      $val="\'\'";
  }
  $loaded{gs}{$key} = $val;
  $saved{gs}{$key} = $val;
  print "Setting server config $key=$val\n" if ($verbose > 0);
  runCommand("$c{zmprov} ms $hn $key $val");
}

sub removeLdapServerConfig($$$) {
  my ($hn,$key,$val) = @_;
  print "Removing server config $key=$val\n" if ($verbose > 0);
  runCommand("$c{zmprov} ms $hn -$key $val");
}

sub addLdapServerConfig($$$) {
  my ($hn,$key,$val) = @_;
  print "Adding server config $key=$val\n" if ($verbose > 0);
  runCommand("$c{zmprov} ms $hn +$key $val");
}

sub getLdapServerConfig($$) {
  my ($key,$hn) = @_;
  $hn = $c{zmail_server_hostname} if ($hn eq ""); 
  my $val;
  return $loaded{gs}{$hn}{$key}
    if (exists $loaded{gs}{$hn}{$key});

  print "$loaded{gs}{$hn}{$key}\n";

  print "Running $c{zmprov} gs $hn\n" if ($verbose > 1);
  unless (open(ZMPROV, "$c{zmprov} gs $hn 2> /dev/null|")) {
    print "Failed to get server config for $hn.\n";
    return;
  }
  my @CONFIG = <ZMPROV>;
  unless (close(ZMPROV)) {
    print "Failed to get server config for $hn. $@\n";
    return;
  }

  while (scalar(@CONFIG) > 0)  {
    chomp(my $line = shift(@CONFIG));
    my ($k, $v) = $line =~ m/^(\w+):\s(.*)/;
    while ($CONFIG[0] !~ m/^\w+:\s.*/ && scalar(@CONFIG) > 0) {
      chomp($v .= shift(@CONFIG));
    }

    next if ($k =~ m/cn|objectClass/);
    $loaded{gs}{$hn}{$k} .= 
      (($loaded{gs}{$hn}{$k} eq "") ? "$v" : " $v");;
  }

  return $loaded{gs}{$hn}{$key};
}

sub setLdapGlobalConfig($$) {
  my ($key,$val) = @_;
  return 
    if (exists $saved{gcf}{$key} && $saved{gcf}{$key} eq $val);
  if ($val eq "") {
      $val="\'\'";
  }
  $loaded{gcf}{$key} = $val;
  $saved{gcf}{$key} = $val;
  print "Setting global config $key=$val\n" if ($verbose > 0);
  runCommand("$c{zmprov} mcf $key $val");
}

sub removeLdapGlobalConfig($$) {
  my ($key,$val) = @_;
  print "Removing global config $key=$val\n" if ($verbose > 0);
  runCommand("$c{zmprov} mcf -$key $val");
}

sub addLdapGlobalConfig($$) {
  my ($key,$val) = @_;
  print "Adding global config $key=$val\n" if ($verbose > 0);
  runCommand("$c{zmprov} mcf +$key $val");
}

sub getLdapGlobalConfig($) {
  my ($key) = @_;
  my ($val); 
  return $loaded{gcf}{$key}
    if (exists $loaded{gcf}{$key});

  print "Getting global config $key=";
  unless (open(ZMPROV, "$c{zmprov} gcf $key 2> /dev/null|")) {
    print "Failed to get global config key $key.\n";
    return;
  }
  my @CONFIG = <ZMPROV>;
  close(ZMPROV);

  while (scalar(@CONFIG) > 0)  {
    chomp(my $line = shift(@CONFIG));
    my ($k, $v) = $line =~ m/^(\w+):\s(.*)/;
    while ($CONFIG[0] !~ m/^\w+:\s.*/ && scalar(@CONFIG) > 0) {
      chomp($v .= shift(@CONFIG));
    }

    next if ($k =~ m/cn|objectClass/);
    $val .= (($val eq "") ? "$v" : " $v") if ($k eq $key);
    $loaded{gcf}{$k} .= 
      (($loaded{gcf}{$k} eq "") ? "$v" : " $v");;
  }
  print "$loaded{gcf}{$key}\n";
  return $loaded{gcf}{$key};
}

sub runCommand {
  my $cmd = shift;
  my $rc;
  $rc = 0xffff & system("$cmd > /dev/null 2>&1 ");
  return $rc;
}

sub isLdapRunning {
  if (index($c{ldap_url}, "/".$c{zmail_server_hostname}) != -1) {
    my $isrunning = 0xffff & system("$c{zmail_home}/bin/ldap status > /dev/null 2>&1");
    return ($isrunning)?0:1;
  } 
}

sub startLdap {
  print "Starting ldap...";
  if (&isLdapRunning) {
    print "already running.\n";
    return;
  }
  $rc = runCommand("$c{zmail_home}/bin/ldap start");
  if ($rc==0) {
    print "done.\n";
  } else {
    print "failed.\n";
    exit 1;
  }
}
