#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2012 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
ulimit -n 32768
ulimit -c unlimited
ulimit -v unlimited
export LD_PRELOAD=/opt/zmail/tcmalloc/lib/libtcmalloc_minimal.so

umask 027
source /opt/zmail/bin/zmshutil || exit 1
zmsetvars \
	zmail_home 

if [ ! -x /opt/zmail/openldap/sbin/slapindex ]; then
	exit 0
fi

u=`id -un`
if [ $u != ${zmail_user} ]; then
    echo "Error: must be run as ${zmail_user} user"
    exit 1
fi

if [ x$1 = "x-h" -o x$1 = "x--help" ]; then
	echo "USAGE: Indexes LDAP databases"
	echo "Main database: zmslapindex <key>"
	echo "Config database: zmslapindex -c <key>"
	echo "Accesslog database: zmslapindex -a <key>"
	exit 1
fi

D=`date +%Y%m%d%H%M%S`
CONFIG=no
ALOG=no
if [ x$1 = "x-c" ]; then
	CONFIG=yes
	KEY=$2
elif [ x$1 = "x-a" ]; then
	ALOG=yes
	KEY=$2
else
	KEY=$1
fi

if [ x$CONFIG = "xyes" ]; then
	${zmail_home}/openldap/sbin/slapindex -q -F ${zmail_home}/data/ldap/config -n 0 $KEY
	RETVAL=$?
elif [ x$ALOG = "xyes" ]; then
	${zmail_home}/openldap/sbin/slapindex -q -F ${zmail_home}/data/ldap/config -b "cn=accesslog" $KEY
	RETVAL=$?
else
	${zmail_home}/openldap/sbin/slapindex -q -F ${zmail_home}/data/ldap/config -b "" $KEY
	RETVAL=$?
fi

exit $RETVAL
