#!/bin/bash

# Example:
#
# 1. Unzip tzdata20xxx.tar.gz to tzdata subdir.
# 2. Run: zmtzdata2ical -o timezones.ics -y 2011 -e extra-data -t tzdata windows-names
# 3. Install generated timezones.ics under /opt/zmail/conf.
# 4. Restart mailboxd.

exec zmjava org.zmail.common.calendar.ZoneInfo2iCalendar "$@"
